# Generated by Django 5.0 on 2023-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0001_squashed_0047_migrate_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "ordering": (models.OrderBy(models.F("priority"), nulls_last=True),),
                "verbose_name": "post category",
                "verbose_name_plural": "post categories",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategorytranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "post category Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": "date_published",
                "ordering": (
                    models.OrderBy(models.F("pinned"), nulls_last=True),
                    "-date_published",
                    "-date_created",
                ),
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterField(
            model_name="authorentriesplugin",
            name="template_folder",
            field=models.CharField(
                choices=[("plugins", "Default template")],
                default="plugins",
                help_text="Select plugin layout to load for this instance",
                max_length=200,
                verbose_name="Plugin layout",
            ),
        ),
        migrations.AlterField(
            model_name="blogconfigtranslation",
            name="app_title",
            field=models.CharField(
                default="blog", max_length=200, verbose_name="application title"
            ),
        ),
        migrations.AlterField(
            model_name="genericblogplugin",
            name="template_folder",
            field=models.CharField(
                choices=[("plugins", "Default template")],
                default="plugins",
                help_text="Select plugin layout to load for this instance",
                max_length=200,
                verbose_name="Plugin layout",
            ),
        ),
        migrations.AlterField(
            model_name="latestpostsplugin",
            name="template_folder",
            field=models.CharField(
                choices=[("plugins", "Default template")],
                default="plugins",
                help_text="Select plugin layout to load for this instance",
                max_length=200,
                verbose_name="Plugin layout",
            ),
        ),
    ]
